// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    Button: typeof import('./components/UI/Button.vue')['default']
    ButtonPlay: typeof import('./components/game/ButtonPlay.vue')['default']
    CanvasLetters: typeof import('./components/game/CanvasLetters.vue')['default']
    ClickForFire: typeof import('./components/game/ClickForFire.vue')['default']
    CloseSpinner: typeof import('./components/UI/CloseSpinner.vue')['default']
    ComeBack: typeof import('./components/ComeBack.vue')['default']
    DashedList: typeof import('./components/UI/DashedList.vue')['default']
    DebugInput: typeof import('./components/game/DebugInput.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    Home: typeof import('./components/Home.vue')['default']
    IconArrow: typeof import('./components/UI/IconArrow.vue')['default']
    IconBurger: typeof import('./components/IconBurger.vue')['default']
    IconShield: typeof import('./components/game/IconShield.vue')['default']
    IconTime: typeof import('./components/game/IconTime.vue')['default']
    LeaderBoard: typeof import('./components/game/LeaderBoard.vue')['default']
    LeaderBoardForm: typeof import('./components/game/LeaderBoardForm.vue')['default']
    LetterTag: typeof import('./components/game/LetterTag.vue')['default']
    Link2Move: typeof import('./components/UI/Link2Move.vue')['default']
    LoaderLine: typeof import('./components/UI/LoaderLine.vue')['default']
    MainGame: typeof import('./components/game/MainGame.vue')['default']
    MenuNavigation: typeof import('./components/MenuNavigation.vue')['default']
    PageControl: typeof import('./components/PageControl.vue')['default']
    PageLoader: typeof import('./components/PageLoader.vue')['default']
    RobotShooter: typeof import('./components/game/RobotShooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreBoard: typeof import('./components/game/ScoreBoard.vue')['default']
    SkillsMe: typeof import('./components/SkillsMe.vue')['default']
    SoundBar: typeof import('./components/SoundBar.vue')['default']
    StatusBar: typeof import('./components/game/StatusBar.vue')['default']
  }
}
